### ISSUE TITLE
The main character is not shown (unable to play by directly opening `index.html`)

### ISSUE THREAD

**Issue by vimoox** [jackbuehner/MicrosoftEdge-S.U.R.F.#7]
![2022-02-13 (2)](https://user-images.githubusercontent.com/97385746/153755637-d1ea5d85-fc4e-4987-b947-7e1c2dba3db6.png)

**Comment by jackbuehner** [comment]
You will receive CORS errors you try to load the images and some other things from a file:// url. You need to start a local http server or deploy the code somewhere else (e.g. surge.sh). https://surf.jackbuehner.com reflects the latest code.

For example:

1. `git clone https://github.com/jackbuehner/MicrosoftEdge-Surf.git`
2. `npx http-server MicrosoftEdge-Surf`

_This example requires [nodejs](https://nodejs.org/en/download/current) and npm to be installed._
